name: Development CI

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: "Tag to deploy to"

defaults:
  run:
    working-directory: ./

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io

permissions:
  contents: read # for checkout repository
  actions: read # for fetching base branch bundle stats
  pull-requests: write # for comments

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  yarn_install_and_build_dev:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Setup
        uses: actions/setup-node@v3

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/arm/v7
          context: .
          push: false
          tags: latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
